config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'about' => 'home#about'

  get 'question' => 'question#question'
  post 'add_question' => 'question#add_question'
  post 'vote/:id' => 'question#vote', as: :vote
  get 'company' => 'company#company'
  resources :profile
  
  namespace "admin" do
    resources :question
    get 'not_approved' => 'question#not_approved', as: :not_approved
    post 'approve/:id' => 'question#approve', as: :approve
  end
  mount Commontator::Engine => '/commontator'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :ques_type
  belongs_to :company
  has_many :vote
  belongs_to :user, foreign_key: "user_id"
  acts_as_commontable

  def vote!(ip)
   if Vote.exists?(:ip => ip, :question_id => id)
   	 vote = Vote.find_by(:ip => ip, :question_id => id)
   	 vote.delete
   else
     Vote.create(:ip => ip, :question_id => id)
   end
  end

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
  has_many :question
end

app/controllers/admin/question_controller.rb
class Admin::QuestionController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin
  layout :get_admin_layouts

  def index
    @questions = Question.all
  end

  def new
    @question_types = QuestionType.all
    @company_names = Company.all
    question = Question.new
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    if user_signed_in?
      question.user_id = current_user.id
    end
    question.approve = true
    question.save
  end

  def show
  end

  def edit
    @question = Question.find(params[:id])
    @question_types = QuestionType.all
    @company_names = Company.all
  end

  def update
    question = Question.find(params[:id])
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    question.approve = true
    question.save
    redirect_to admin_question_index_path
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    respond_to do |format|
      format.json { render json: { status: "success"} }
    end
  end

  def not_approved
    @questions = Question.where(approve: false)
  end

  def approve
    question = Question.find(params[:id])
    question.approve = true
    question.save
    respond_to do |format|
      format.json { render json: { status: "success"} }
    end
  end

end
def get_admin_layouts
  "admin/layouts/admin"
end


private

  def is_admin
    if user_signed_in?
     if current_user.email == 'kranti_kumar@hotmail.com'
       true
     else
       redirect_to root_path
     end
    else
      redirect_to login_path
    end
  end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  def question
    questions = QuestionType.find_by(question_type: params[:ques_type]).question.where(approve: true)
    @questions = questions.order("created_at DESC").page params[:page]
  end

  def add_question
  	@question_types = QuestionType.all
    @company_names = Company.all
    question = Question.new
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    if user_signed_in?
      question.user_id = current_user.id
    end
    question.approve = false
    question.save
     respond_to do |format|
	    format.json  { render :json => { :status => "ok", :message => "Success" }}
	   end
  end

  def vote
    # raise request.ip.inspect
    @question = Question.find(params[:id])
    @question.vote!(request.ip)
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/admin/question_helper.rb
module Admin::QuestionHelper
end

app/helpers/question_helper.rb
module QuestionHelper
	def question_posted_by(question)
		if question.user_id?
			question.user.email.to_s.split('@')[0].humanize 
		else
			'Guest User'
		end
	end
end

app/views/question/_vote.html.erb
<% question = @question %>
<% if Vote.exists?(:ip => request.ip, :question_id => question.id) %>
	<%= link_to vote_path(question.id), style: "text-decoration: none;", id:"vote-down-#{question.id}", method: 'post', remote: true  do %>
	  <span style="color: #000;"><i class="fa fa-thumbs-up"></i> Like (<%= question.vote.count %>)</span>
	<% end %>
<% else %>
	<%= link_to vote_path(question.id), style: "text-decoration: none;", id: "vote-up-#{question.id}", method: 'post', remote: true  do %>
	  <span><i class="fa fa-thumbs-up"></i> Like (<%= question.vote.count %>)</span>
	<% end %>
<% end %>

app/views/question/question.html.erb
<style type="text/css">
  .active-menu-qus a{
    background-color: #080808;
    color: #fff !important;
  }
</style>
<div class="row">
  <h2><%= params[:ques_type] %></h2>
  <p class="header-line"></p>
</div>
<div class="alert alert-success">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>Congratulations!</strong> Right Answer.
</div>
<div class="alert alert-danger">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong>Oops!</strong> Wrong Answer.
</div>
<% @questions.shuffle.each_with_index do |question, i| %>
  <% if (i+1) % 3 == 0 %>
    <div class="row">
      <div class="col-sm-12">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- questions_page_1 -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1440938179169907"
             data-ad-slot="9063260270"
             data-ad-format="auto"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </div>
    </div>
    <hr>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <div>
        <h5><%= question.question %></h5>
      </div>
      <div class="options">
        <div class="col-sm-6">
          <span style="position: absolute; padding: 1px;"></span>
          <span class="question-radio" data-option="<%= question.option1 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option1 %></span>
        </div>
        <div class="col-sm-6">
          <span style="position: absolute; padding: 1px;"></span>
          <span class="question-radio" data-option="<%= question.option2 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option2 %></span>
        </div>
        <div class="col-sm-6">
          <span style="position: absolute; padding: 1px;"></span>
          <span class="question-radio" data-option="<%= question.option3 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option3 %></span>
        </div>
        <div class="col-sm-6">
          <span style="position: absolute; padding: 1px;"></span>
          <span class="question-radio" data-option="<%= question.option4 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option4 %></span>
        </div>
        <span class="answer_<%= question.id %>" data-ans="<%= question.answer %>"></span>
      </div>
      <div class="col-sm-12" style="margin-top:15px; padding: 0;">
        <div class="col-sm-2 link" id="vote<%= question.id %>">
          <% if Vote.exists?(:ip => request.ip, :question_id => question.id) %>
            <%= link_to vote_path(question.id), style: "text-decoration: none;", method: 'post', remote: true  do %>
              <span style="color: #000;"><i class="fa fa-thumbs-up"></i> Like (<%= question.vote.count %>)</span>
            <% end %>
          <% else %>
            <%= link_to vote_path(question.id), style: "text-decoration: none;", method: 'post', remote: true  do %>
              <span><i class="fa fa-thumbs-up"></i> Like (<%= question.vote.count %>)</span>
            <% end %>
          <% end %>
        </div>
        <div class="col-sm-3 link">
          <span id="comment_<%= question.id %>"><i class="fa fa-comments"></i> Comments (<%= question.thread.filtered_comments.count.to_s %>)</span>
        </div>
        <div class="col-sm-3 link">
          <%= link_to company_path(company_name: company_name(question.company_id)), style: "text-decoration: none;" do %>
          <span><i class="fa fa-folder-open"></i> <%= company_name(question.company_id) %></span>
          <% end %>
        </div>
        <div class="col-sm-4 link">
          <span><i class="fa fa-user"></i> <%= question_posted_by(question) %></span>
        </div>
      </div>
      <div id="comment_box_<%= question.id %>">
        <div class="row">
          <div class="col-sm-12">
            <div class="comment_box">
              <%= commontator_thread(question) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr>
<script type="text/javascript">
  $('#comment_box_<%= question.id %>').hide()
  $('#comment_<%= question.id %>').on("click", function(){
    if($('#comment_box_<%= question.id %>').is(':visible')){
      $("#comment_box_<%= question.id %>").slideUp();
      $('#comment_<%= question.id %> span').css("color", "#777");
    }
    else{
      $("#comment_box_<%= question.id %>").slideDown();
      $('#comment_<%= question.id %> span').css("color", "#000");
    }
  });
</script>
<% end %>
<%= paginate @questions %>
<script type="text/javascript">
  // answer check start
  $('.question-radio').on('click', function(){
    user_ans = $(this).data('option');
    user_id = $(this).data('id');
    answer = $('.answer_'+user_id).data('ans')
    if(user_ans == answer)
    {
      $(this).prev().html('<div class="right-ans"></div>');
      $(".alert-success").fadeTo(2000, 500).slideUp(500);
    }
    else
    {
      $(this).prev().html('<div class="wrong-ans"></div>');
      $(".alert-danger").fadeTo(2000, 500).slideUp(500);
    }
  });
  // answer check end
</script>

app/views/question/vote.js.erb
$("#vote<%= @question.id %>").html("<%= j render(partial: 'vote') %>")