config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'about' => 'home#about'

  get 'question' => 'question#question'
  post 'add_question' => 'question#add_question'
  post 'vote/:id' => 'question#vote', as: :vote
  get 'company' => 'company#company'
  resources :profile
  
  namespace "admin" do
    resources :question
    get 'not_approved' => 'question#not_approved', as: :not_approved
    post 'approve/:id' => 'question#approve', as: :approve
  end
  mount Commontator::Engine => '/commontator'

end

app/views/shared/_left_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to root_path, :class=>"logo" do %>
      <%= image_tag "ampattern.png", id:'logo' %>
    <% end %>
  </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav">
<!--     <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu message-dropdown">
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-preview">
          <a href="#">
            <div class="media">
              <span class="pull-left">
                <img class="media-object" src="http://placehold.it/50x50" alt="">
              </span>
              <div class="media-body">
                <h5 class="media-heading"><strong>John Smith</strong>
                </h5>
                <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                <p>Lorem ipsum dolor sit amet, consectetur...</p>
              </div>
            </div>
          </a>
        </li>
        <li class="message-footer">
          <a href="#">Read All New Messages</a>
        </li>
      </ul>
    </li> -->
<!--     <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
      <ul class="dropdown-menu alert-dropdown">
        <li>
          <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
        </li>
        <li>
          <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
        </li>
        <li class="divider"></li>
        <li>
          <a href="#">View All</a>
        </li>
      </ul>
    </li> -->
    <li class="dropdown">
      <a href="#" data-toggle="modal" data-target="#myModal">
        <i class="fa fa-plus-square-o"></i> Add Questions
      </a>
    </li>
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email.to_s.split('@')[0].humanize %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% if false %>
            <li>
              <%= link_to profile_index_path do %>
                <i class="fa fa-fw fa-user"></i> Profile
              <% end %>
            </li>
          <% end %>
          <!-- <li>
            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
          </li> -->
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-fw fa-gear"></i> Settings</a>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to destroy_user_session_path, method: 'DELETE' do %>
              <i class="fa fa-fw fa-power-off"></i> Log Out
            <% end %>
          </li>
        </ul>
      </li>
    <% else %>
    <li>
      <%= link_to "Log In", new_user_session_path %>
    </li>
    <li>
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
    
    <% end %>
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li class="active-menu-home">
        <%= link_to root_path do %>
          <i class="fa fa-fw fa-home"></i> Home 
        <% end %>
      </li>
      <li class="active-menu-qus">
        <a href="javascript:;" data-toggle="collapse" data-target="#practice"><i class="fa fa-fw fa-arrows-v"></i> Practice Papers <i class="fa fa-fw fa-caret-down"></i></a>
        <ul id="practice" class="collapse">
          <li>
            <%= link_to 'Aptitude Questions', question_path(ques_type: 'Aptitude Questions') %>
          </li>
          <li>
            <%= link_to 'English Questions', question_path(ques_type: 'English Questions') %>
          </li>
          <li>
            <%= link_to 'Computer Questions', question_path(ques_type: 'Computer Questions') %>
          </li>
          <li>
            <%= link_to 'Reasoning Questions', question_path(ques_type: 'Reasoning Questions') %>
          </li>
        </ul>
      </li>
      <li class="active-menu-cmpy">
        <a href="javascript:;" data-toggle="collapse" data-target="#placement"><i class="fa fa-fw fa-arrows-v"></i> Companies <i class="fa fa-fw fa-caret-down"></i></a>
        <ul id="placement" class="collapse">
          <li>
            <%= link_to 'IBM Questions', company_path(company_name: 'IBM') %>
          </li>
          <li>
            <%= link_to 'TCS Questions', company_path(company_name: 'TCS') %>
          </li>
          <li>
            <%= link_to 'CTS Questions', company_path(company_name: 'CTS') %>
          </li>
          <li>
            <%= link_to 'HCL Questions', company_path(company_name: 'HCL') %>
          </li>
          <li>
            <%= link_to 'IGate Questions', company_path(company_name: 'IGate') %>
          </li>
          <li>
            <%= link_to 'Wipro Questions', company_path(company_name: 'Wipro') %>
          </li>
          <li>
            <%= link_to 'Genpact Questions', company_path(company_name: 'Genpact') %>
          </li>
          <li>
            <%= link_to 'Huawei Questions', company_path(company_name: 'Huawei') %>
          </li>
          <li>
            <%= link_to 'Infosys Questions', company_path(company_name: 'Infosys') %>
          </li>
          <li>
            <%= link_to 'Accenture Questions', company_path(company_name: 'Accenture') %>
          </li>
          <li>
            <%= link_to 'Capgemini Questions', company_path(company_name: 'Capgemini') %>
          </li>
          <li>
            <%= link_to 'Hexaware Questions', company_path(company_name: 'Hexaware') %>
          </li>
        </ul>
      </li>
      <!-- <li>
        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-bullhorn"></i> Students Speak </a>
      </li> -->
     <!--  <li>
        <a href="bootstrap-grid.html"><i class="fa fa-fw fa-graduation-cap"></i> Off Campus Drives </a>
      </li> -->
      <li class="active-menu-about">
        <%= link_to about_path do %>
          <i class="fa fa-fw fa-info"></i> About Us 
        <% end %>
      </li>
      <ul>
      </div>
      <!-- /.navbar-collapse -->
    </nav>

app/views/shared/_seo.html.erb
<meta content="Practice questions for MNC interviews and competitive examinations." name="description">
<meta content="amcat Latest test pattern, amcat solved questions, amcat sample papers, amcat question papers, amcat questions with solutions, Elitmus questions, amcat questions" name="keywords">
<meta content="http://www.ampattern.com/" name="Author">
<meta content="INDEX,FOLLOW" name="ROBOTS">
<meta property="fb:app_id" content="1597357363850386" /> 
<meta property="og:type" content="website" /> 
<meta property="og:url" content="http://www.ampattern.com/" /> 
<meta property="og:title" content="AMPattern" /> 
<meta property="og:image" content="<%= asset_path"fb-ampattern.png" %>" /> 
<meta property="og:description" content="Practice questions for MNC interviews and competitive examinations." />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75827367-1', 'auto');
  ga('send', 'pageview');

</script>