config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'
  get 'about' => 'home#about'

  get 'question' => 'question#question'
  post 'add_question' => 'question#add_question'
  post 'vote/:id' => 'question#vote', as: :vote
  get 'company' => 'company#company'
  resources :profile
  
  namespace "admin" do
    resources :question
    get 'not_approved' => 'question#not_approved', as: :not_approved
    post 'approve/:id' => 'question#approve', as: :approve
  end
  mount Commontator::Engine => '/commontator'

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :ques_type
  belongs_to :company
  has_many :vote
  belongs_to :user, foreign_key: "user_id"
  acts_as_commontable

  def vote!(ip)
   if Vote.exists?(:ip => ip, :question_id => id)
   	 vote = Vote.find_by(:ip => ip, :question_id => id)
   	 vote.delete
   else
     Vote.create(:ip => ip, :question_id => id)
   end
  end

end

app/models/question_type.rb
class QuestionType < ActiveRecord::Base
  has_many :question
end

app/controllers/admin/question_controller.rb
class Admin::QuestionController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin
  layout :get_admin_layouts

  def index
    @questions = Question.all
  end

  def new
    @question_types = QuestionType.all
    @company_names = Company.all
    question = Question.new
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    if user_signed_in?
      question.user_id = current_user.id
    end
    question.approve = true
    question.save
  end

  def show
  end

  def edit
    @question = Question.find(params[:id])
    @question_types = QuestionType.all
    @company_names = Company.all
  end

  def update
    question = Question.find(params[:id])
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    question.approve = true
    question.save
    redirect_to admin_question_index_path
  end

  def destroy
    question = Question.find(params[:id])
    question.destroy
    respond_to do |format|
      format.json { render json: { status: "success"} }
    end
  end

  def not_approved
    @questions = Question.where(approve: false)
  end

  def approve
    question = Question.find(params[:id])
    question.approve = true
    question.save
    respond_to do |format|
      format.json { render json: { status: "success"} }
    end
  end

end
def get_admin_layouts
  "admin/layouts/admin"
end


private

  def is_admin
    if user_signed_in?
     if current_user.email == 'kranti_kumar@hotmail.com'
       true
     else
       redirect_to root_path
     end
    else
      redirect_to login_path
    end
  end

app/controllers/question_controller.rb
class QuestionController < ApplicationController

  def question
    questions = QuestionType.find_by(question_type: params[:ques_type]).question.where(approve: true)
    @questions = questions.order("created_at DESC").page params[:page]
  end

  def add_question
  	@question_types = QuestionType.all
    @company_names = Company.all
    question = Question.new
    question.question = params[:question]
    question.option1 = params[:option_a]
    question.option2 = params[:option_b]
    question.option3 = params[:option_c]
    question.option4 = params[:option_d]
    question.answer = params[:answer]
    question.question_type_id = params[:type]
    question.company_id = params[:campony]
    if user_signed_in?
      question.user_id = current_user.id
    end
    question.approve = false
    question.save
     respond_to do |format|
	    format.json  { render :json => { :status => "ok", :message => "Success" }}
	   end
  end

  def vote
    # raise request.ip.inspect
    @question = Question.find(params[:id])
    @question.vote!(request.ip)
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/admin/question_helper.rb
module Admin::QuestionHelper
end

app/helpers/question_helper.rb
module QuestionHelper
	def question_posted_by(question)
		if question.user_id?
			question.user.email.to_s.split('@')[0].humanize 
		else
			'Guest User'
		end
	end
end

app/views/admin/question/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="top-25">
      <%= form_tag(admin_question_path, {:method => :PATCH}) do %>
        <div>
          <%= label_tag(:question, "Question") %>
          <%= text_area_tag(:question, @question.question) %>
        </div>
        <div>
          <%= label_tag(:option_a, "Option A") %>
          <%= text_field_tag(:option_a, @question.option1) %>
        </div>
        <div>
          <%= label_tag(:option_b, "Option B") %>
          <%= text_field_tag(:option_b, @question.option2) %>
        </div>
        <div>
          <%= label_tag(:option_c, "Option C") %>
          <%= text_field_tag(:option_c, @question.option3) %>
        </div>
        <div>
          <%= label_tag(:option_d, "Option D") %>
          <%= text_field_tag(:option_d, @question.option4) %>
        </div>
        <div>
          <%= label_tag(:answer, "Answer") %>
          <%= text_field_tag(:answer, @question.answer) %>
        </div>
        <div>
          <%= label_tag(:campony, "Company Name" ) %>
          <%= select_tag(:campony, options_for_select(@company_names.collect{ |c| [c.name, c.id]})) %>
        </div>
        <div>
          <%= label_tag(:type, "Question Type") %>
          <%= select_tag(:type, options_for_select(@question_types.collect{ |q| [q.question_type, q.id]})) %>
        </div>
        <%= submit_tag 'Save' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/question/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="top-25">
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Congratulations!</strong> Right Answer.
      </div>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Oops!</strong> Wrong Answer.
      </div>
      <%#= @questions.inspect %>
      <div class="row">
        <table id="myTable">
          <thead>
            <tr>
              <th>SN</th>
              <th>Question</th>
            </tr>
          </thead>
          <tbody>
            <% @questions.each_with_index do |question, i| %>
              <tr>
                <td><%= i+1 %></td>
                <td>
                  <div>
                    <p><%= question.question %></p>
                  </div>
                  <div class="row options">
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option1 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option1 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option2 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option2 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option3 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option3 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option4 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option4 %></span>
                    </div>
                    <span class="answer_<%= question.id %>" data-ans="<%= question.answer %>"></span>
                  </div>
                  <hr>
                  <div class="row"  style="font-size:11px">
                    <div class="col-sm-2">
                      <p>Answer: <%= question.answer %></p>
                    </div>
                    <div class="col-sm-2">
                      <p>Question Type: <%= question_name(question.question_type_id).to_s.split(' ')[0]   %></p>
                    </div>
                    <div class="col-sm-2">
                      <p>Company: <%= company_name(question.company_id) %></p>
                    </div>
                    <div class="col-sm-2">
                      <p>Posted by: <%= question_posted_by(question) %></p>
                    </div>
                    <div class="col-sm-2">
                      <span><%= link_to 'Edit', edit_admin_question_path(question) %></span> | 
                      <span><%= link_to 'Delete', admin_question_path(question), method: 'DELETE', remote: true, class:'ques_delete' %></span>
                    </div>
                    <div class="col-sm-2">
                      <span><%= link_to 'Edit', edit_admin_question_path(question) %></span> | 
                      <span><%= link_to 'Delete', admin_question_path(question), method: 'DELETE', remote: true, class:'ques_delete' %></span>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#myTable').DataTable();
    });
  $('.ques_delete').on('click', function(){
    $(this).parent().parent().parent().fadeOut()
  })
  $('.ques_approve').on('click', function(){
    $(this).parent().parent().parent().fadeOut()
  })
  // answer check start
  $('.question-radio').on('click', function(){
    user_ans = $(this).data('option');
    user_id = $(this).data('id');
    answer = $('.answer_'+user_id).data('ans')
    if(user_ans == answer)
    {
      $(this).prev().html('<div class="right-ans"></div>');
      $(".alert-success").fadeTo(2000, 500).slideUp(500);
    }
    else
    {
      $(this).prev().html('<div class="wrong-ans"></div>');
      $(".alert-danger").fadeTo(2000, 500).slideUp(500);
    }
  });
  // answer check end
</script>

app/views/admin/question/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="top-25">
      <%= form_tag(new_admin_question_path, {:method => :get}) do %>
        <div>
          <%= label_tag(:question, "Question") %>
          <%= text_area_tag(:question) %>
        </div>
        <div>
          <%= label_tag(:option_a, "Option A") %>
          <%= text_field_tag(:option_a) %>
        </div>
        <div>
          <%= label_tag(:option_b, "Option B") %>
          <%= text_field_tag(:option_b) %>
        </div>
        <div>
          <%= label_tag(:option_c, "Option C") %>
          <%= text_field_tag(:option_c) %>
        </div>
        <div>
          <%= label_tag(:option_d, "Option D") %>
          <%= text_field_tag(:option_d) %>
        </div>
        <div>
          <%= label_tag(:answer, "Answer") %>
          <%= text_field_tag(:answer) %>
        </div>
        <div>
          <%= label_tag(:campony, "Company Name" ) %>
          <%= select_tag(:campony, options_for_select(@company_names.collect{ |c| [c.name, c.id]})) %>
        </div>
        <div>
          <%= label_tag(:type, "Question Type") %>
          <%= select_tag(:type, options_for_select(@question_types.collect{ |q| [q.question_type, q.id]})) %>
        </div>
        <%= submit_tag 'Save' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/question/not_approved.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="top-25">
      <div class="alert alert-success">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Congratulations!</strong> Right Answer.
      </div>
      <div class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Oops!</strong> Wrong Answer.
      </div>
      <%#= @questions.inspect %>
      <div class="row">
        <table id="myTable">
          <thead>
            <tr>
              <th>SN</th>
              <th>Question</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @questions.each_with_index do |question, i| %>
              <tr>
                <td><%= i+1 %></td>
                <td>
                  <div>
                    <p><%= question.question %></p>
                  </div>
                  <div class="row options">
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option1 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option1 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option2 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option2 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option3 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option3 %></span>
                    </div>
                    <div class="col-sm-6">
                      <span style="position: absolute; padding: 1px;"></span>
                      <span class="question-radio" data-option="<%= question.option4 %>" data-id="<%= question.id %>"><input type="radio" name="option" style="margin-right:5px;" /><%= question.option4 %></span>
                    </div>
                    <span class="answer_<%= question.id %>" data-ans="<%= question.answer %>"></span>
                  </div>
                  <hr>
                  <div class="row"  style="font-size:11px">
                    <div class="col-sm-3">
                      <p>Answer: <%= question.answer %></p>
                    </div>
                    <div class="col-sm-3">
                      <p>Question Type: <%= question_name(question.question_type_id).to_s.split(' ')[0]   %></p>
                    </div>
                    <div class="col-sm-3">
                      <p>Company: <%= company_name(question.company_id) %></p>
                    </div>
                    <div class="col-sm-3">
                      <p>Posted by: <%= question_posted_by(question) %></p>
                    </div>
                  </div>
                </td>
                <td>
                  <p><%= link_to 'Edit', edit_admin_question_path(question) %></p>
                  <p><%= link_to 'Delete', admin_question_path(question), method: 'DELETE', remote: true, class:'ques_delete' %></p>
                  <p><%= link_to 'Approve', admin_approve_path(question), method: 'POST', remote: true, class:'ques_approve' %></p>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    $('#myTable').DataTable();
    });
  $('.ques_delete').on('click', function(){
    $(this).parent().parent().parent().fadeOut()
  })
  $('.ques_approve').on('click', function(){
    $(this).parent().parent().parent().fadeOut()
  })
  // answer check start
  $('.question-radio').on('click', function(){
    user_ans = $(this).data('option');
    user_id = $(this).data('id');
    answer = $('.answer_'+user_id).data('ans')
    if(user_ans == answer)
    {
      $(this).prev().html('<div class="right-ans"></div>');
      $(".alert-success").fadeTo(2000, 500).slideUp(500);
    }
    else
    {
      $(this).prev().html('<div class="wrong-ans"></div>');
      $(".alert-danger").fadeTo(2000, 500).slideUp(500);
    }
  });
  // answer check end
</script>